version: 2.1

orbs:
  guardian: bishopfox/guardian@0

workflows:
  ci:
    jobs:
      - guardian/preflight:
          filters:
            branches:
              ignore: ["master", "staging"]
      - guardian/ginkgo:
          requires:
            - guardian/preflight

  release:
    jobs:
      - guardian/publish:
          docker: false
          candidate: false
          release_name: "aws-signing"
          filters:
            branches:
              only:
                - master
