name: production

on:
  push:
    branches:
      - 'master'

env:
  SERVICE: 'aws-signing'
  ENV_NAME: "stage"
  GO_VERSION: 'v1.16.5'
  DOCKER: 'false'
  AWS_ROLE_TO_ASSUME: ''
  AWS_REGION: 'us-east-1'
  AWS_ACCOUNT_ID: ''
  NEEDS_AWS_CREDENTIALS: 'false'
  PLATFORMS: ''
  DOCKER_PATH: ''
  BUILDX: 'false'
  REPO: ''
  ARTIFACT_PATHS: ''

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Copy Changelog
        run: |
          if [[ ! -d dist ]]; then
            mkdir dist
          fi

          if [[ -f CHANGELOG.md ]]; then
            cp CHANGELOG.md dist/CHANGELOG.md
          fi
        shell: bash

      - name: Extract Version
        if: env.DOCKER == 'true'
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
        shell: bash

      - name: Set Tag Based on Branch
        if: env.DOCKER == 'true'
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          BRANCH_NAME="${{ github.head_ref }}"
          else
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          fi

          if [[ "$BRANCH_NAME" == "main" || "$BRANCH_NAME" == "master" ]]; then
          echo "TAG=${VERSION}" >> $GITHUB_ENV
          else
          echo "TAG=${VERSION}-${GITHUB_SHA:0:7}" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Set up Docker Buildx
        if: env.DOCKER == 'true'
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        if: env.DOCKER == 'true'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubActionsPlan
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        if: env.DOCKER == 'true'
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: "${{ env.AWS_ACCOUNT_ID }}"
          mask-password: 'true'

      - name: Build, tag, and push image to Amazon ECR
        if: env.DOCKER == 'true'
        run: |
          if [ "${{ env.NEEDS_AWS_CREDENTIALS }}" = "true" ]; then
            echo "Using Docker Buildx with AWS credentials"
            docker buildx build --platform ${{ env.PLATFORMS }} -t ${{ env.TAG }} ${{ env.DOCKER_PATH }} --load \
            --build-arg AWS_ACCESS_KEY_ID=${{ secret.AWS_ACCESS_KEY_ID }} \
            --build-arg AWS_SECRET_ACCESS_KEY=${{ secret.AWS_SECRET_ACCESS_KEY }} \
            --build-arg AWS_REGION=${{ env.AWS_REGION }} \
            --load
          elif [ "${{ env.BUILDX }}" = "true" ]; then
            echo "Using Docker Buildx without AWS credentials"
            docker buildx build --platform ${{ env.PLATFORMS }} -t ${{ env.TAG }} ${{ env.DOCKER_PATH }} --load
          else
            echo "Using standard Docker build"
            docker build -t ${{ env.TAG }} ${{ env.DOCKER_PATH }}
          fi

          docker tag ${{ env.TAG }} ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.REPO }}:${{ env.TAG }}
          docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.REPO }}:${{ env.TAG }}
        shell: bash

      - name: Persist build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ${{ env.ARTIFACT_PATHS }}